### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by li-aolong** [wzy6642/ProCo#1]
> Previous work: Large Language Models are Better Reasoners with Self-Verification (Weng et al., 2023) [Arxiv](https://arxiv.org/abs/2212.09561) [EMNLP 2023](https://aclanthology.org/2023.findings-emnlp.167/)

The core method of ProCo, _**substitute verification**_, is **identical** to the method in **_Large Language Models are Better Reasoners with Self-Verification_** by Weng et al. (2023). 

The main difference lies in the approach Weng et al. (2023) use to generate the initial answer, where multiple answers are generated and the original question is masked for verification, eventually leading to one final answer. In contrast, ProCo generates one answer at a time, iterating multiple times to arrive at the final answer. Additionally, for the question masking method, both ProCo and Weng et al. (2023) use two types. Weng et al. (2023) refer to them as **True-False Item Verification** and **Condition Mask Verification**, and ProCo’s classification is essentially the same.

Weng et al. (2023):
![image](https://github.com/user-attachments/assets/6ebde8c0-0aae-476e-ad64-e220c77aaa9d)

ProCo:
![image](https://github.com/user-attachments/assets/8770be99-5249-4435-89a8-7a6e08c9790a)
![image](https://github.com/user-attachments/assets/1a6589e5-58d3-4140-a2f7-4ff6e8039d10)

Questions:
1. Have you seen this paper?
2. If you have, why was it not cited?
3. How would you evaluate the high similarity between the core methods of ProCo and Weng et al. (2023)?

**Comment by wzy6642** [comment]
The primary distinction between our work and Self-Verification lies in the following aspects:

1. Self-Verification employs the Best-of-N decoding method, which instructs LLMs to generate multiple solutions, score each using a scoring function, and select the highest-scoring solution as the final answer. However, the Best-of-N method fails when the correct answer is not included in the generated sample set. In contrast, ProCo utilizes an iterative verify-then-correct framework that progressively identifies and corrects (probably) erroneous responses to achieve the correct one. This approach avoids the repetition of previous mistakes and incrementally enhances response quality.

2. Self-Verification randomly selects conditions to mask during the process. By contrast, ProCo introduces a key condition identification method, which improves the accuracy of the substitute verification process.

Notably, the differences between Self-Verification and ProCo are substantial, as reflected in their methodologies and effectiveness. Additionally, I have not read this paper.

**Comment by WENGSYX** [comment]
As one of the authors of Self-Verification, I feel compelled to address the concerns raised in this issue.

After thorough discussion with the ProCo authors, I would like to clarify several points regarding the relationship between these works:


**1. Methodological Comparison:**

Self-Verification introduced several key innovations in LLM answer verification by proposing a novel Best-of-N decoding strategy for generating and evaluating multiple candidate answers, pioneering work in condition masking for answer verification, and developing a scoring mechanism to effectively select the most accurate response from multiple candidates. While ProCo shares some technical foundations with Self-Verification in terms of condition masking and verification approaches, it differs by focusing on iterative improvement of a single answer rather than multiple-answer selection, implementing specific key condition identification methods, and developing a verify-then-correct framework for progressive answer refinement.
Self-Verification focuses on verifying the correctness of LLM-generated answers by assigning a score. If the LLM produces multiple potential answers, Self-Verification helps identify the most accurate one. ProCo, on the other hand, aims to generate "potentially incorrect answers" so that the LLM can become aware of its mistakes and refine its original responses. While Self-Verification is centered on verification rather than correction, ProCo's primary goal is to guide the LLM toward producing improved, more accurate answers.

ProCo was inspired by observations drawn from Self-Correct (Huang et al., ICLR 2024). ProCo aims to develop a more effective "correction" strategy (rather than mere verification) for general reasoning tasks, using nearly all datasets tested in Self-Correct. Compared to the conclusions drawn from Self-Correct, ProCo makes a significant contribution by enabling LLMs to correct their own reasoning responses.

**2. Citation and Future Acknowledgment:**

**The ProCo authors have acknowledged their awareness of Self-Verification during their research process.** While the lack of citation in the current version was an oversight, they have committed to contact the EMNLP Program Committee to update their paper with appropriate citations to Self-Verification, include proper acknowledgment of Self-Verification's foundational contributions, and maintain awareness and appropriate citations of Self-Verification in their future work in this research direction.
Both teams have engaged in constructive dialogue and are committed to maintaining academic integrity. We appreciate the community's attention to these important issues and believe this resolution will benefit the broader research community.
